services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090'
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
