services:

  postgres:
    image: 'postgres:16'
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example_spring

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'

  node-exporter:
    image: 'prom/node-exporter:latest'
    ports:
      - '9100'

  postgres-exporter:
    image: 'prometheuscommunity/postgres-exporter:latest'
    ports:
      - '9187'
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090'
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/ #配置grafana的prometheus数据源、dashboard
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
